### ISSUE TITLE
Значения вводятся дважды

### ISSUE THREAD

**Issue by oleg-tgn** [KnyazevDaniil/OAiP_labs_Knyazev#11]
scanf("%f", &miles); // первый раз без проверки

f = scanf("%d", &miles); // тут уже с проверкой

**Comment by KnyazevDaniil** [comment]
изменил строчку
printf("Enter miles ", &miles);
	
	miles = scanf("%d", &miles);

**Comment by oleg-tgn** [comment]
так не будет корректно работать
miles = scanf("%d", &miles);

проверяйте
