### ISSUE TITLE
Как можно еще выполнить задержку экрана

### ISSUE THREAD

**Issue by oleg-tgn** [KnyazevDaniil/OAiP_labs_Knyazev#6]
iostream все же библиотека C++
какой еще есть способ выполнить задержку экрана? смотрите способ в учебнике Полякова

**Comment by KnyazevDaniil** [comment]
добрый вечер, отвечаю на ваш вопрос, задержку экрана можно сделать командой getch(), при этом подключить библиотеку conio.h

**Comment by KnyazevDaniil** [comment]
команда
getchar ();


>Вторник, 26 сентября 2017, 23:31 +03:00 от oleg-tgn <notifications@github.com>:
>
>Closed  #6 .
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Даниил Князев
